-- MySQL Script generated by MySQL Workbench
-- qui 14 nov 2019 17:33:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `password` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `permission` TINYINT NOT NULL DEFAULT 1,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `cnpj` VARCHAR(25) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NULL,
  `km_initial` DOUBLE NOT NULL,
  `km_current` DOUBLE NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `chassis` VARCHAR(45) NOT NULL,
  `license_plate` VARCHAR(45) NOT NULL,
  `company_id` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicle_company1_idx` (`company_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `chassis_UNIQUE` (`chassis` ASC),
  UNIQUE INDEX `license_plate_UNIQUE` (`license_plate` ASC),
  CONSTRAINT `fk_vehicle_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_company` (
  `user_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `permission` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`, `company_id`),
  INDEX `fk_User_has_Company_Company1_idx` (`company_id` ASC),
  INDEX `fk_User_has_Company_User_idx` (`user_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_User_has_Company_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Company_Company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicle_usage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicle_usage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  `description` VARCHAR(140) NOT NULL,
  `initial_date` DATETIME NOT NULL,
  `final_date` DATETIME NOT NULL,
  `usage_status` TINYINT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `user_id`, `vehicle_id`),
  INDEX `fk_user_has_vehicle_vehicle1_idx` (`vehicle_id` ASC),
  INDEX `fk_user_has_vehicle_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_vehicle_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_vehicle_vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `mydb`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`report_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(80) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `registry_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registry_registry_type1_idx` (`registry_type_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_registry_registry_type1`
    FOREIGN KEY (`registry_type_id`)
    REFERENCES `mydb`.`report_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicle_usage_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicle_usage_report` (
  `vehicle_usage_id` INT NOT NULL,
  `registry_id` INT NOT NULL,
  PRIMARY KEY (`vehicle_usage_id`, `registry_id`),
  INDEX `fk_vehicle_usage_has_registry_registry1_idx` (`registry_id` ASC),
  INDEX `fk_vehicle_usage_has_registry_vehicle_usage1_idx` (`vehicle_usage_id` ASC),
  CONSTRAINT `fk_vehicle_usage_has_registry_vehicle_usage1`
    FOREIGN KEY (`vehicle_usage_id`)
    REFERENCES `mydb`.`vehicle_usage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_usage_has_registry_registry1`
    FOREIGN KEY (`registry_id`)
    REFERENCES `mydb`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attachment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(80) NULL,
  `description` VARCHAR(45) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attachment_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attachment_report` (
  `attachment_id` INT NOT NULL,
  `report_id` INT NOT NULL,
  PRIMARY KEY (`attachment_id`, `report_id`),
  INDEX `fk_attachment_has_report_report1_idx` (`report_id` ASC),
  INDEX `fk_attachment_has_report_attachment1_idx` (`attachment_id` ASC),
  CONSTRAINT `fk_attachment_has_report_attachment1`
    FOREIGN KEY (`attachment_id`)
    REFERENCES `mydb`.`attachment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attachment_has_report_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `mydb`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`expanse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`expanse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `value` DOUBLE NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report_has_expanse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`report_has_expanse` (
  `report_id` INT NOT NULL,
  `expanse_id` INT NOT NULL,
  PRIMARY KEY (`report_id`, `expanse_id`),
  INDEX `fk_report_has_expanse_expanse1_idx` (`expanse_id` ASC),
  INDEX `fk_report_has_expanse_report1_idx` (`report_id` ASC),
  CONSTRAINT `fk_report_has_expanse_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `mydb`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_has_expanse_expanse1`
    FOREIGN KEY (`expanse_id`)
    REFERENCES `mydb`.`expanse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
