-- MySQL Script generated by MySQL Workbench
-- sáb 14 mar 2020 14:10:32 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema frotaicrop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema frotaicrop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frotaicrop` DEFAULT CHARACTER SET ascii ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`manutencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manutencao` (
  `idmanutencao` INT NOT NULL,
  `data` VARCHAR(45) NULL,
  `intervalo_manutencao` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idmanutencao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(3) NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `logradouro` VARCHAR(80) NULL,
  `coordenada` POINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`foto` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL DEFAULT '\"\"',
  `url` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fazenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fazenda` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `area_ha` DOUBLE NULL,
  `exibir` TINYINT NULL,
  `cnpj` VARCHAR(15) NULL,
  `ie` VARCHAR(15) NULL,
  `telefone_fazenda` VARCHAR(15) NULL,
  `email_fazenda` VARCHAR(45) NULL,
  `email_financeiro` VARCHAR(45) NULL,
  `endereco_cobranca` VARCHAR(45) NULL,
  `delimitacao` POLYGON NULL,
  `endereco_id` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `logo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  UNIQUE INDEX `ie_UNIQUE` (`ie` ASC),
  INDEX `fk_fazenda_endereco1_idx` (`endereco_id` ASC),
  INDEX `fk_fazenda_foto1_idx` (`logo_id` ASC),
  CONSTRAINT `fk_fazenda_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `mydb`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fazenda_foto1`
    FOREIGN KEY (`logo_id`)
    REFERENCES `mydb`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frotaicrop`.`modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`modelos` (
  `idmodelos` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `ano` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `familia` VARCHAR(45) NULL,
  `sub_familia` VARCHAR(45) NULL,
  `numero_frota` INT NULL,
  PRIMARY KEY (`idmodelos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frotaicrop`.`maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`maquinas` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `datacadastro` DATETIME NULL,
  `nome` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL,
  `potencia` INT NULL,
  `rotacao` INT NULL,
  `torque` INT NULL,
  `cilindrada` FLOAT NULL,
  `peso` INT NULL,
  `status` TINYINT(2) NULL,
  `lastro` INT NULL,
  `tanque` INT NULL,
  `pneu` VARCHAR(15) COLLATE 'utf8mb4_unicode_ci' NULL,
  `reservatorque` INT NULL,
  `filipado` TINYINT(2) NULL,
  `cabinado` TINYINT(2) NULL,
  `sisprecisao` TINYINT(2) NULL,
  `data` DATETIME NULL,
  `compbarra` DECIMAL(8,2) NULL,
  `cappulverizador` DECIMAL(8,2) NULL,
  `reservatorioagua` DECIMAL(8,2) NULL,
  `pressaotrabalho` DECIMAL(8,2) NULL,
  `vazaomax` DECIMAL(8,2) NULL,
  `trilha` DECIMAL(8,2) NULL,
  `tubodescarga` DECIMAL(8,2) NULL,
  `arealimpeza` DECIMAL(8,2) NULL,
  `comprimento` DECIMAL(8,2) NULL,
  `largura` DECIMAL(8,2) NULL,
  `captanquegrao` DECIMAL(8,2) NULL,
  `vazaodescarga` DECIMAL(8,2) NULL,
  `larguraplatafor1` DECIMAL(8,2) NULL,
  `culturaplat1` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL,
  `larguraplatafor2` DECIMAL(8,2) NULL,
  `culturaplat2` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL,
  `larguraplatafor3` DECIMAL(8,2) NULL,
  `culturaplat3` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL,
  `manutencao_idmanutencao` INT NULL,
  `fazenda_id` INT NOT NULL,
  `foto_id` INT NULL,
  `modelos_idmodelos` INT NOT NULL,
  PRIMARY KEY (`id`, `modelos_idmodelos`),
  INDEX `fk_equipamentos_manutencao1_idx` (`manutencao_idmanutencao` ASC),
  INDEX `fk_equipamentos_fazenda1_idx` (`fazenda_id` ASC),
  INDEX `fk_maquinas_foto1_idx` (`foto_id` ASC),
  INDEX `fk_maquinas_modelos1_idx` (`modelos_idmodelos` ASC),
  CONSTRAINT `fk_equipamentos_manutencao1`
    FOREIGN KEY (`manutencao_idmanutencao`)
    REFERENCES `mydb`.`manutencao` (`idmanutencao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipamentos_fazenda1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `mydb`.`fazenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maquinas_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `mydb`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maquinas_modelos1`
    FOREIGN KEY (`modelos_idmodelos`)
    REFERENCES `frotaicrop`.`modelos` (`idmodelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`integracao_direta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`integracao_direta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ibeacon` VARCHAR(45) NULL,
  `IdPosition` INT NULL,
  `IdTrackedUnit` INT NULL,
  `Ignition` INT NULL,
  `Available` INT NULL,
  `ValidGPS` INT NULL,
  `EventDate` DATETIME NULL,
  `UpdateDate` DATETIME NULL,
  `Driver` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NULL,
  `Latitude` POINT NULL,
  `Longitude` POINT NULL,
  `velocidade` DOUBLE NULL,
  `direcao` INT NULL,
  `nsatelite` INT NULL,
  `odometro` DOUBLE NULL,
  `bateria` DOUBLE NULL,
  `horimetro` DOUBLE NULL,
  `batbackup` DOUBLE NULL,
  `maquinas_modelos_idmodelos` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `integra_rpxes_idtrackedunit_index` (`IdTrackedUnit` ASC),
  INDEX `fk_integracao_direta_maquinas1_idx` (`maquinas_modelos_idmodelos` ASC),
  CONSTRAINT `fk_integracao_direta_maquinas1`
    FOREIGN KEY (`maquinas_modelos_idmodelos`)
    REFERENCES `frotaicrop`.`maquinas` (`modelos_idmodelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 94297
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`integra_rpxes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`integra_rpxes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdPositionTrailer` INT NULL,
  `IdTrackedUnitType` INT NULL,
  `TrackedUnitIntegrationCode` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL,
  `IdPosition` INT NULL,
  `IdTrackedUnit` INT NULL,
  `TrackedUnit` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL,
  `IdEvent` INT NULL,
  `Ignition` INT NULL,
  `Available` INT NULL,
  `ValidGPS` INT NULL,
  `EventDate` DATETIME NULL,
  `UpdateDate` DATETIME NULL,
  `Driver` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL,
  `Latitude` POINT NULL,
  `Longitude` POINT NULL,
  `Address` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL,
  `velocidade` DOUBLE NULL,
  `direcao` VARCHAR(10) COLLATE 'utf8mb4_unicode_ci' NULL,
  `nsatelite` INT NULL,
  `odometro` DOUBLE NULL,
  `bateria` DOUBLE NULL,
  `horimetro` DOUBLE NULL,
  `batbackup` DOUBLE NULL,
  `maquinas_modelos_idmodelos` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `integra_rpxes_idtrackedunit_index` (`IdTrackedUnit` ASC),
  INDEX `fk_integra_rpxes_maquinas1_idx` (`maquinas_modelos_idmodelos` ASC),
  CONSTRAINT `fk_integra_rpxes_maquinas1`
    FOREIGN KEY (`maquinas_modelos_idmodelos`)
    REFERENCES `frotaicrop`.`maquinas` (`modelos_idmodelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 94297
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(140) NULL,
  `email` VARCHAR(45) NULL,
  `nivel_permissao` TINYINT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `integracao_direta_id` INT(10) UNSIGNED NOT NULL,
  `integra_rpxes_id` INT(10) UNSIGNED NOT NULL,
  `Username_integracao_rpx` VARCHAR(45) NULL,
  `Password_integracao_rpx` VARCHAR(45) NULL,
  `HashAuth_integracao_rpx` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`usuario` ASC),
  INDEX `fk_usuario_integracao_direta1_idx` (`integracao_direta_id` ASC),
  INDEX `fk_usuario_integra_rpxes1_idx` (`integra_rpxes_id` ASC),
  CONSTRAINT `fk_usuario_integracao_direta1`
    FOREIGN KEY (`integracao_direta_id`)
    REFERENCES `frotaicrop`.`integracao_direta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_integra_rpxes1`
    FOREIGN KEY (`integra_rpxes_id`)
    REFERENCES `frotaicrop`.`integra_rpxes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frotaicrop`.`implementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`implementos` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `datacadastro` DATETIME NULL,
  `nome` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL,
  `horas` INT NULL,
  `lat` POINT NULL,
  `long` POINT NULL,
  `qtdlinha` INT NULL,
  `capfertilizante` INT NULL,
  `capsemente` INT NULL,
  `potenciareq` INT NULL,
  `peso` INT NULL,
  `largurautil` INT NULL,
  `compbarra` INT NULL,
  `cappulverizador` INT NULL,
  `reservatorioagua` INT NULL,
  `pressaotrabalho` INT NULL,
  `vazaomax` INT NULL,
  `pesomaxp` INT NULL,
  `volume` INT NULL,
  `descarga` INT NULL,
  `pesomaxb` INT NULL,
  `largurab` INT NULL,
  `comprimentob` INT NULL,
  `ndisco` INT NULL,
  `pesomaxg` INT NULL,
  `potenciareqg` INT NULL,
  `largurag` INT NULL,
  `volumed` INT NULL,
  `rotacaod` INT NULL,
  `capacidaded` INT NULL,
  `largurad` INT NULL,
  `comprimentod` INT NULL,
  `larguratrab` INT NULL,
  `pesoo` INT NULL,
  `comprimentoo` INT NULL,
  `largurao` INT NULL,
  `capacidademaxo` INT NULL,
  `manutencao_idmanutencao` INT NOT NULL,
  `fazenda_id` INT NOT NULL,
  `foto_id` INT NULL,
  `modelos_idmodelos` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_implementos_manutencao1_idx` (`manutencao_idmanutencao` ASC),
  INDEX `fk_implementos_fazenda1_idx` (`fazenda_id` ASC),
  INDEX `fk_implementos_foto1_idx` (`foto_id` ASC),
  INDEX `fk_implementos_modelos1_idx` (`modelos_idmodelos` ASC),
  CONSTRAINT `fk_implementos_manutencao1`
    FOREIGN KEY (`manutencao_idmanutencao`)
    REFERENCES `mydb`.`manutencao` (`idmanutencao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_implementos_fazenda1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `mydb`.`fazenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_implementos_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `mydb`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_implementos_modelos1`
    FOREIGN KEY (`modelos_idmodelos`)
    REFERENCES `frotaicrop`.`modelos` (`idmodelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `idinventario` INT NOT NULL,
  `numero_equipamento` INT NULL,
  `grupo_responsavel` VARCHAR(45) NULL,
  `subgrupo_responsavel` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `grupo_` VARCHAR(45) NULL,
  `implementos_id` INT(10) UNSIGNED NOT NULL,
  `equipamentos_id` INT(10) UNSIGNED NOT NULL,
  `prazo_utilizacao` DATETIME NULL,
  `data_ultima_localizacao` DATETIME NULL,
  `data_ultima_devolucao` DATETIME NULL,
  PRIMARY KEY (`idinventario`),
  INDEX `fk_inventario_implementos1_idx` (`implementos_id` ASC),
  INDEX `fk_inventario_equipamentos1_idx` (`equipamentos_id` ASC),
  CONSTRAINT `fk_inventario_implementos1`
    FOREIGN KEY (`implementos_id`)
    REFERENCES `frotaicrop`.`implementos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_equipamentos1`
    FOREIGN KEY (`equipamentos_id`)
    REFERENCES `frotaicrop`.`maquinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `rg` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `estado_civil` TINYINT NOT NULL,
  `nacionalidade` VARCHAR(3) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cargo` VARCHAR(45) NULL,
  `usuario_id` INT NULL,
  `endereco_id` INT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `foto_id` INT NOT NULL,
  `inventario_idinventario` INT NOT NULL,
  PRIMARY KEY (`id`, `inventario_idinventario`),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_pessoa_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_pessoa_endereco1_idx` (`endereco_id` ASC),
  INDEX `fk_pessoa_foto1_idx` (`foto_id` ASC),
  INDEX `fk_pessoa_inventario1_idx` (`inventario_idinventario` ASC),
  CONSTRAINT `fk_pessoa_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `mydb`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `mydb`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_inventario1`
    FOREIGN KEY (`inventario_idinventario`)
    REFERENCES `mydb`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dispositivo_iot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dispositivo_iot` (
  `id` INT NOT NULL,
  `idx_dispositivo` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `localizacao` POINT NULL,
  `data_instalacao` DATE NULL,
  `ocorrencias` VARCHAR(200) NULL,
  `numero_chip` VARCHAR(45) NULL,
  `numero_imei` VARCHAR(45) NULL,
  `valor_mensal` DOUBLE NULL,
  `tipo` VARCHAR(45) NULL,
  `numero_satelite` VARCHAR(15) NULL,
  `versao_firmware` VARCHAR(45) NULL,
  `data_expira_contrato_sat_chip` DATETIME NULL,
  `ultima_comunicacao` DATETIME NULL,
  `ttn_appeui` VARCHAR(45) NULL,
  `ttn_appkey` VARCHAR(45) NULL,
  `ttn_application_id` VARCHAR(45) NULL,
  `ttn_device_id` VARCHAR(45) NULL,
  `pasta_ftp` VARCHAR(45) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `instalador_id` INT NOT NULL,
  `foto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_dispositivo_UNIQUE` (`idx_dispositivo` ASC),
  INDEX `fk_dispositivo_iot_pessoa1_idx` (`instalador_id` ASC),
  INDEX `fk_dispositivo_iot_foto1_idx` (`foto_id` ASC),
  CONSTRAINT `fk_dispositivo_iot_pessoa1`
    FOREIGN KEY (`instalador_id`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dispositivo_iot_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `mydb`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parcela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parcela` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `solo` VARCHAR(45) NULL,
  `data_plantio` DATETIME NULL,
  `data_inicio_manejo` DATETIME NULL,
  `geolocalizacao` POINT NULL,
  `delimitacao` POLYGON NULL,
  `area` DOUBLE NULL,
  `umidade_inicio_solo` VARCHAR(45) NULL,
  `excesso_maior` VARCHAR(45) NULL,
  `manter_cc` VARCHAR(45) NULL,
  `espacamento_linha` FLOAT NULL,
  `espacamento_plantas` FLOAT NULL,
  `cultura` VARCHAR(45) NULL,
  `equipamento_descricao` VARCHAR(45) NULL,
  `fazenda_id` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_parcela_fazenda1_idx` (`fazenda_id` ASC),
  CONSTRAINT `fk_parcela_fazenda1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `mydb`.`fazenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dispositivo_iot_parcela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dispositivo_iot_parcela` (
  `dispositivo_iot_id` INT NOT NULL,
  `parcela_id` INT NOT NULL,
  PRIMARY KEY (`dispositivo_iot_id`, `parcela_id`),
  INDEX `fk_dispositivo_iot_has_parcela_parcela1_idx` (`parcela_id` ASC),
  INDEX `fk_dispositivo_iot_has_parcela_dispositivo_iot1_idx` (`dispositivo_iot_id` ASC),
  CONSTRAINT `fk_dispositivo_iot_has_parcela_dispositivo_iot1`
    FOREIGN KEY (`dispositivo_iot_id`)
    REFERENCES `mydb`.`dispositivo_iot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dispositivo_iot_has_parcela_parcela1`
    FOREIGN KEY (`parcela_id`)
    REFERENCES `mydb`.`parcela` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estacao_cebola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estacao_cebola` (
  `id` INT NOT NULL,
  `idx_dispositivo` VARCHAR(15) NOT NULL,
  `temperatura` FLOAT NULL,
  `umidade` FLOAT NULL,
  `velociade_vento` FLOAT NULL,
  `luminosidade` FLOAT NULL,
  `uv` FLOAT NULL,
  `direcao_vento` FLOAT NULL,
  `pluviometro_0` FLOAT NULL,
  `pluviometro_1` FLOAT NULL,
  `umidade_solo_0` FLOAT NULL,
  `umidade_solo_1` FLOAT NULL,
  `umidade_solo_2` FLOAT NULL,
  `temperatura_solo_0` FLOAT NULL,
  `temperatura_solo_1` FLOAT NULL,
  `temperatura_solo_2` FLOAT NULL,
  `temperatura_superficial` FLOAT NULL,
  `umidade_superficial` FLOAT NULL,
  `molhamento_foliar` FLOAT NULL,
  `status_bateria` FLOAT NULL,
  `localizacao` POINT NULL,
  `dispositivo_iot_id` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_estacao_cebola_dispositivo_iot1_idx` (`dispositivo_iot_id` ASC),
  UNIQUE INDEX `idx_dispositivo_UNIQUE` (`idx_dispositivo` ASC),
  CONSTRAINT `fk_estacao_cebola_dispositivo_iot1`
    FOREIGN KEY (`dispositivo_iot_id`)
    REFERENCES `mydb`.`dispositivo_iot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estacao_icrop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estacao_icrop` (
  `id` INT NOT NULL,
  `idx_estacao` VARCHAR(15) NULL,
  `senha` VARCHAR(45) NULL,
  `uv` FLOAT NULL,
  `absbaro` FLOAT NULL,
  `action` VARCHAR(45) NULL,
  `backup` INT(5) NULL,
  `dailyrain` FLOAT NULL,
  `datareal` VARCHAR(45) NULL,
  `dateutc` VARCHAR(45) NULL,
  `dewpoint` FLOAT NULL,
  `inhumi` FLOAT NULL,
  `intemp` FLOAT NULL,
  `light` FLOAT NULL,
  `monthlyrain` FLOAT NULL,
  `outhumi` FLOAT NULL,
  `outemp` FLOAT NULL,
  `rainrate` FLOAT NULL,
  `realtime` FLOAT NULL,
  `relbaro` FLOAT NULL,
  `rtfreq` FLOAT NULL,
  `softwaretype` FLOAT NULL,
  `weeklyrain` FLOAT NULL,
  `windchill` FLOAT NULL,
  `winddir` FLOAT NULL,
  `windgust` FLOAT NULL,
  `windspeed` FLOAT NULL,
  `yearlyrain` FLOAT NULL,
  `dispositivo_iot_id` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_estacao_icrop_dispositivo_iot1_idx` (`dispositivo_iot_id` ASC),
  CONSTRAINT `fk_estacao_icrop_dispositivo_iot1`
    FOREIGN KEY (`dispositivo_iot_id`)
    REFERENCES `mydb`.`dispositivo_iot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa_fazenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa_fazenda` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fazenda_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `consultor` TINYINT(1) NOT NULL DEFAULT 0,
  `proprietario` TINYINT(1) NOT NULL DEFAULT 0,
  `responsavel_financeiro` TINYINT(1) NOT NULL DEFAULT 0,
  `responsavel` TINYINT(1) NOT NULL DEFAULT 0,
  `chefe_regional` TINYINT(1) NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `fazenda_id`),
  INDEX `fk_usuario_has_fazenda_fazenda1_idx` (`fazenda_id` ASC),
  INDEX `fk_pessoa_fazenda_pessoa1_idx` (`pessoa_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_usuario_has_fazenda_fazenda1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `mydb`.`fazenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_fazenda_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(15) NULL,
  `celular` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contato_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_contato_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrato` (
  `id` INT ZEROFILL NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_final` DATETIME NOT NULL,
  `visitas_contrato` TINYINT NULL,
  `fazenda_id` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_contrato_fazenda1_idx` (`fazenda_id` ASC),
  CONSTRAINT `fk_contrato_fazenda1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `mydb`.`fazenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estacao_icrop_has_maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estacao_icrop_has_maquinas` (
  `estacao_icrop_id` INT NOT NULL,
  `maquinas_id` INT(10) UNSIGNED NOT NULL,
  `maquinas_modelos_idmodelos` INT NOT NULL,
  PRIMARY KEY (`estacao_icrop_id`, `maquinas_id`, `maquinas_modelos_idmodelos`),
  INDEX `fk_estacao_icrop_has_maquinas_maquinas1_idx` (`maquinas_id` ASC, `maquinas_modelos_idmodelos` ASC),
  INDEX `fk_estacao_icrop_has_maquinas_estacao_icrop1_idx` (`estacao_icrop_id` ASC),
  CONSTRAINT `fk_estacao_icrop_has_maquinas_estacao_icrop1`
    FOREIGN KEY (`estacao_icrop_id`)
    REFERENCES `mydb`.`estacao_icrop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacao_icrop_has_maquinas_maquinas1`
    FOREIGN KEY (`maquinas_id` , `maquinas_modelos_idmodelos`)
    REFERENCES `frotaicrop`.`maquinas` (`id` , `modelos_idmodelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `frotaicrop` ;

-- -----------------------------------------------------
-- Table `frotaicrop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `remember_token` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `usernamerpx` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `passwordrpx` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `hashrpx` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`fazendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`fazendas` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `proprietario` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nomefaz` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `cnpj` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `ie` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `enderecofazenda` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `telefonefazenda` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `responsavel` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `emailfazenda` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `respfinanceiro` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `emailfinanceiro` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `datacontrato` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `validadecontrato` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `area` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `kml` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fazendas_nomefaz_unique` (`nomefaz` ASC),
  INDEX `fazendas_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `fazendas_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `frotaicrop`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`imagems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`imagems` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `imagem` BLOB NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`operacaos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`operacaos` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `velocidade_adequada_max` DECIMAL(8,2) NOT NULL,
  `velocidade_adequada_min` DECIMAL(8,2) NOT NULL,
  `velocidade_critica_max` DECIMAL(8,2) NOT NULL,
  `velocidade_critica_min` DECIMAL(8,2) NOT NULL,
  `usa_clima` TINYINT(1) NOT NULL,
  `data` DATETIME NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`log_operacaos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`log_operacaos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `operacao_id` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `fazenda` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_equip` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_imple` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `data` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_pos` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `operacaos_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_log_operacaos_operacaos1_idx` (`operacaos_id` ASC),
  CONSTRAINT `fk_log_operacaos_operacaos1`
    FOREIGN KEY (`operacaos_id`)
    REFERENCES `frotaicrop`.`operacaos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`password_resets` (
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`pessoas` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomecompl` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tppessoa` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `dtnasci` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nacional` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `estcivil` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `cpf` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `rg` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `telefone` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `celular` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `endcompl` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `estado` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `pais` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `usuario` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `senha` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `repsenha` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `valacesso` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pessoas_cpf_unique` (`cpf` ASC),
  INDEX `pessoas_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `pessoas_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `frotaicrop`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`talhaos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`talhaos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomefaz` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nomearea` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `area` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `arquivo` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `fazenda_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `talhaos_user_id_foreign` (`user_id` ASC),
  INDEX `talhaos_fazenda_id_foreign` (`fazenda_id` ASC),
  CONSTRAINT `talhaos_fazenda_id_foreign`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `frotaicrop`.`fazendas` (`id`),
  CONSTRAINT `talhaos_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `frotaicrop`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`equipamentos_has_implementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`equipamentos_has_implementos` (
  `equipamentos_id` INT(10) UNSIGNED NOT NULL,
  `implementos_id` INT(10) UNSIGNED NOT NULL,
  `fazenda_id` INT NOT NULL,
  PRIMARY KEY (`equipamentos_id`, `implementos_id`),
  INDEX `fk_equipamentos_has_implementos_implementos1_idx` (`implementos_id` ASC),
  INDEX `fk_equipamentos_has_implementos_equipamentos1_idx` (`equipamentos_id` ASC),
  INDEX `fk_equipamentos_has_implementos_fazenda1_idx` (`fazenda_id` ASC),
  CONSTRAINT `fk_equipamentos_has_implementos_equipamentos1`
    FOREIGN KEY (`equipamentos_id`)
    REFERENCES `frotaicrop`.`maquinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipamentos_has_implementos_implementos1`
    FOREIGN KEY (`implementos_id`)
    REFERENCES `frotaicrop`.`implementos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipamentos_has_implementos_fazenda1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `mydb`.`fazenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`maquinas_has_operacaos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`maquinas_has_operacaos` (
  `maquinas_id` INT(10) UNSIGNED NOT NULL,
  `operacaos_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`maquinas_id`, `operacaos_id`),
  INDEX `fk_maquinas_has_operacaos_operacaos1_idx` (`operacaos_id` ASC),
  INDEX `fk_maquinas_has_operacaos_maquinas1_idx` (`maquinas_id` ASC),
  CONSTRAINT `fk_maquinas_has_operacaos_maquinas1`
    FOREIGN KEY (`maquinas_id`)
    REFERENCES `frotaicrop`.`maquinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maquinas_has_operacaos_operacaos1`
    FOREIGN KEY (`operacaos_id`)
    REFERENCES `frotaicrop`.`operacaos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frotaicrop`.`maquinas_has_estacao_cebola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frotaicrop`.`maquinas_has_estacao_cebola` (
  `maquinas_id` INT(10) UNSIGNED NOT NULL,
  `maquinas_modelos_idmodelos` INT NOT NULL,
  `estacao_cebola_id` INT NOT NULL,
  PRIMARY KEY (`maquinas_id`, `maquinas_modelos_idmodelos`, `estacao_cebola_id`),
  INDEX `fk_maquinas_has_estacao_cebola_estacao_cebola1_idx` (`estacao_cebola_id` ASC),
  INDEX `fk_maquinas_has_estacao_cebola_maquinas1_idx` (`maquinas_id` ASC, `maquinas_modelos_idmodelos` ASC),
  CONSTRAINT `fk_maquinas_has_estacao_cebola_maquinas1`
    FOREIGN KEY (`maquinas_id` , `maquinas_modelos_idmodelos`)
    REFERENCES `frotaicrop`.`maquinas` (`id` , `modelos_idmodelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maquinas_has_estacao_cebola_estacao_cebola1`
    FOREIGN KEY (`estacao_cebola_id`)
    REFERENCES `mydb`.`estacao_cebola` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
