-- MySQL Script generated by MySQL Workbench
-- sáb 16 nov 2019 10:10:45 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema radar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema radar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `radar` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_uso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_uso` (
  `id` INT(11) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `radar` ;

-- -----------------------------------------------------
-- Table `radar`.`fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radar`.`fabricante` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `fipe_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `radar`.`loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radar`.`loja` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `cidade` VARCHAR(32) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `radar`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radar`.`veiculo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fabricante_id` INT(11) NULL DEFAULT NULL,
  `loja_id` INT(11) NOT NULL,
  `qrcode` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(32) NULL DEFAULT NULL,
  `placa` VARCHAR(16) NULL DEFAULT NULL,
  `chassi` VARCHAR(128) NULL DEFAULT NULL,
  `modelo` VARCHAR(128) NOT NULL,
  `tanque` DOUBLE NULL DEFAULT NULL,
  `ano` INT NULL DEFAULT NULL,
  `ano_modelo` INT NULL,
  `km_cadastro` DOUBLE NULL DEFAULT NULL,
  `km_atual` DOUBLE NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `cor` VARCHAR(45) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `qrcode_id` (`qrcode` ASC),
  INDEX `fabricante_id` (`fabricante_id` ASC),
  INDEX `loja_id` (`loja_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `estoque_ibfk_2`
    FOREIGN KEY (`fabricante_id`)
    REFERENCES `radar`.`fabricante` (`id`),
  CONSTRAINT `estoque_ibfk_4`
    FOREIGN KEY (`loja_id`)
    REFERENCES `radar`.`loja` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `radar`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radar`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `loja_id` INT(11) NOT NULL,
  `usuario` VARCHAR(128) NOT NULL,
  `nome` VARCHAR(128) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(128) NOT NULL,
  `nivel_permissao` TINYINT NOT NULL DEFAULT 1,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario` (`usuario` ASC),
  UNIQUE INDEX `cpf` (`cpf` ASC),
  INDEX `loja_id` (`loja_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`loja_id`)
    REFERENCES `radar`.`loja` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `radar`.`uso_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radar`.`uso_veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `veiculo_id` INT(11) NOT NULL,
  `tipo_uso_id` INT NOT NULL,
  `km_inicial` DOUBLE NULL DEFAULT NULL,
  `km_final` DOUBLE NULL,
  `tanque_inicio` DOUBLE NULL DEFAULT NULL,
  `tanque_final` DOUBLE NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `status` TINYINT NOT NULL,
  `data_inicial` DATETIME NOT NULL,
  `data_final` DATETIME NOT NULL,
  INDEX `funcionario_id` (`usuario_id` ASC),
  INDEX `fk_uso_veiculo_tipo_uso1_idx` (`tipo_uso_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_uso_veiculo_veiculo1_idx` (`veiculo_id` ASC),
  CONSTRAINT `log_ibfk_4`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `radar`.`usuario` (`id`),
  CONSTRAINT `fk_uso_veiculo_tipo_uso1`
    FOREIGN KEY (`tipo_uso_id`)
    REFERENCES `mydb`.`tipo_uso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uso_veiculo_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `radar`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
